
sudo: require

language: cpp

cache: ccache

dist: focal

branches:
  only:
    - master

compiler:
  - gcc
  - clang

arch:
  - amd64
  - arm64

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-9

script: 
  - cmake . && make
  - ./get_code_cov.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)